/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.jupiter.api.Test;

import java.util.stream.Collectors;

import static java.lang.System.out;
import static org.junit.jupiter.api.Assertions.*;

public class FibonacciTest {
    @Test public void testFib() {
        Fibonacci.generate().limit(20).forEach(nr -> out.print(nr + " "));
        System.out.println();
        Fibonacci.iterate().limit(20).forEach(nr -> out.print(nr + " "));
    }
}
